package com.learnJava8.stream.numberStream;

import java.util.stream.IntStream;

public class NumericStreamRangeCountExamples {

	public static void main(String[] args) {
		IntStream.range(1, 5).forEach(i -> System.out.println("Generated int values [" + i + "] using range() \n"));
		System.out.println("Count [" + IntStream.range(1, 5).count() + "] of numbers generated by range() \n");
		
		IntStream.rangeClosed(1, 5).forEach( i -> System.out.println("Generated int values [" + i + "] using rangeClosed() \n"));
		System.out.println("Count [" + IntStream.rangeClosed(1, 5).count() + "] of numbers generated by rangeClosed() \n");
		
		IntStream.rangeClosed(1, 5).asDoubleStream().forEach(d -> System.out.println("Generated double values [" + d + "] using range() \n"));
		IntStream.rangeClosed(1, 5).asLongStream().forEach(l -> System.out.println("Generated long values [" + l + "] using range() \n"));
	}
}
